config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :labels
  end

  root 'tasks#index'
  resources :tasks
  resources :users
  resources :sessions
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy

  before_destroy :destroy_action
  before_update :update_action

  before_validation { email.downcase! }
    validates :name, length:{ in: 1..30 }
    validates :email, length:{ in: 1..255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: true
  has_secure_password
  validates :password, length: { minimum: 6 }

  private
  def destroy_action
    if User.where(admin: true).count == 1 && self.admin
      throw :abort
    end
  end

  def update_action
    # if User.where(admin: true).count == 1 && self.admin == false
    @admin_users = User.where(admin: true)
    # 権限持っている人は複数いるかも。今ログインしている人は一番上ではないかも
    if (@admin_users.count == 1 && @admin_users.first == self) && self.admin == false
      #errors.add バリデーションメッセージの役割
      errors.add :base, "管理者が一人も居ない状態にはできません！"
      throw :abort
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy, :show]
  before_action :checking_admin

  def index
    @users = User.select(:id, :name, :email, :admin).order("created_at").page(params[:page]).per(10)
  end

  def show
    @tasks = @user.tasks.all
    @tasks = @tasks.page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path(@user.id), notice: "ユーザー登録しました"
    else
      render :new, notice: "ユーザー登録ができませんでした"
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path(@user.id), notice: "ユーザー情報を更新しました"
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: "#{@user.name}さんのアカウントを削除しました"
    else
      redirect_to admin_users_path, notice: "管理者は最低１人必要の為、#{@user.name}さんのアカウントを削除できません"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def checking_admin
    if current_user.nil? || !current_user.admin?
      redirect_to tasks_path, notice: "管理者以外はアクセスできません。"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user_login, only: [:new]
  before_action :user_check, only: [:show]
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'ログインしました'
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def check_user_login
    if logged_in?
      redirect_to tasks_path, notice:"ログイン中です。まずログアウトしてください。"
    end
  end

  def user_check
    user = User.find(params[:id])
    if current_user.id != user.id
      redirect_to tasks_path, notice: "権限がありません"
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h2>ユーザー情報編集画面</h2>
  <%= form_with(model: [:admin, @user], local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div class="field">
    <%= form.label :管理者権限 %>
      <%= form.check_box :admin %>
    </div>
    <div class="field">
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>
    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>
    <div class="field">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
    </div>

    <%= form.submit "更新", class: "btn btn-primary" %>
  <% end %>

<%= link_to 'ユーザー一覧画面へ戻る', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Manyoユーザー一覧</h1>

<table>
  <tr>
    <th>ユーザーID</th>
    <th>名前</th>
    <th>管理者権限</th>
    <th>投稿タスク数</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.admin %></td>
      <td><%= user.tasks.count %></td>
      <td><%= link_to '詳細', admin_user_path(user.id) %></td>
      <td><%= link_to '編集', edit_admin_user_path(user.id), data: { confirm: '本当に編集していいですか？' } %></td>
      <td><%= link_to '削除', admin_user_path(user.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "新規ユーザー登録", new_admin_user_path %></p>

<%= paginate @users %>

app/views/admin/users/new.html.erb
<h2>管理者用　新規ユーザー登録画面</h2>
<%= form_with(model: [:admin, @user], local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div class="field">
    <%= form.label :管理者権限 %>
      <%= form.check_box :admin %>
    </div>
    <div class="field">
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>
    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>
    <div class="field">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
    </div>

    <%= form.submit "登録", class: "btn btn-primary" %>
  <% end %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<% if @user == current_user %>
  <%= link_to 'タスク登録', new_task_path %>
  <%= link_to 'プロフィール編集', edit_user_path %>
  <% end %>
</div>
<br>

<h2>プロフイール情報</h2>
<table>
  <tr>
    <th>名前</th>
    <th>メールアドレス</th>
    <th>管理者権限</th>
  </tr>

  <tr>
    <td><%= @user.name %></td>
    <td><%= @user.email %></td>
    <td><%= @user.admin %></td>
  </tr>
</table>

<h2>タスク一覧</h2>
<table>
  <tr>
    <th>タスク名</th>
    <th>タスク詳細</th>
    <th>作成日</th>
    <th>終了期限</th>
    <th>ステータス</th>
    <th>優先順位</th>
  </tr>

  <% @user.tasks.each do |task| %>
    <tr>
      <td><%= task.list %></td>
      <td><%= task.detail %></td>
      <td><%= task.created_at %></td>
      <td><%= task.expired_at %></td>
      <td><%= task.status %></td>
      <td><%= task.priority %></td>
      <td><%= link_to '詳細', task_path(task.id) %></td>
      <td><%= link_to '編集', edit_task_path(task.id), data: { confirm: '本当に編集していいですか？' } %></td>
      <td><%= link_to '削除', task_path(task.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'ユーザー一覧画面へ戻る', admin_users_path %>